# Modified from the [Default TagBot template in PkgTemplates](https://github.com/JuliaCI/PkgTemplates.jl/blob/master/templates/github/workflows/TagBot.yml)
# Trigger TagBot only if
name: TagBot

on:
  repository_dispatch:
    types: [trigger-tagbot]
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        default: "3"
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
# For public repo, this is all you need.
# For private repo, you have to add `with: token: TAG_BLABLABLA` of created PAT named `TAG_BLABLABLA` for example with permissions:
# - Read access to actions, deployments, discussions, issues, metadata, pages, and pull requests
# - Read and Write access to code (that is, contents)
jobs:
  TagBot:
    if: github.event_name == 'repository_dispatch' # Add this condition if `github.event.client_payload` is applied in the followings  to guarantee client_payload exists. Check also `PLUGIN_TAGBOT()` and register.yml
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          changelog: |
            ## {{ package }} {{ version }}
            ${{ github.event.client_payload.logfile_msg }}
            {% if previous_release %}
            [Diff since {{ previous_release }}]({{ compare_url }})
            {% endif %}
            {% if custom %}
            {{ custom }}
            {% endif %}
            {% if issues %}
            **Closed issues:**
            {% for issue in issues %}
            - {{ issue.title }} (#{{ issue.number }})
            {% endfor %}
            {% endif %}
            {% if pulls %}
            **Merged pull requests:**
            {% for pull in pulls %}
            - {{ pull.title }} (#{{ pull.number }}) (@{{ pull.author.username }})
            {% endfor %}
            {% endif %}

          registry: okatsn/OkRegistry
  TagBotNoChangelog: # KEYNOTE: Manually run this to tag previous versions
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          registry: okatsn/OkRegistry
